### ISSUE TITLE
Auto Scanner Exception

### ISSUE THREAD

**Issue by bassrock** [l3uddz/plex_autoscan#11]
I keep getting the following in my plex_auto_scan logs:

```
2017-11-02 18:29:09,495 -    ERROR -     UTILS [ 3350]: Exception checking for process: 'Plex Media Scanner': 
Traceback (most recent call last):
  File "/plexscanner/plex_autoscan/utils.py", line 43, in is_process_running
    if process.name().lower() == process_name.lower():
  File "/usr/local/lib/python2.7/site-packages/psutil/__init__.py", line 641, in name
    name = self._proc.name()
  File "/usr/local/lib/python2.7/site-packages/psutil/_psbsd.py", line 504, in wrapper
    raise ZombieProcess(self.pid, self._name, self._ppid)
ZombieProcess: psutil.ZombieProcess process still exists but it's a zombie (pid=1079)
```

It seems that when I do see that occur artwork for movies don't show up in plex.

**Comment by l3uddz** [comment]
sorry for late reply. cant say ive come across this issue. is it still happening with the latest versions of autoscan? if so will look into it further.

**Comment by bassrock** [comment]
I have still seen this come up. It is in a FreeBSD Jail. The same jail that I have running plex.

**Comment by l3uddz** [comment]
ok well in dev branch i have made it catch the psutil.ZombieProcess exception and consider the Plex Media Scanner as not running.

**Comment by bassrock** [comment]
Ok awesome thank you!
