### ISSUE TITLE
Failed to validate Google Drive Access Token

### ISSUE THREAD

**Issue by tyhi** [l3uddz/plex_autoscan#149]
**Describe the bug**
Starting plex_autoscan server, give error: 

`AUTOSCAN [139761290172160]: Failed to validate Google Drive Access Token.`

I've authorized and it successfully exchanged for an access token when running 

`python3 scan.py authorize`

**To Reproduce**
1. `python3 scan.py authorize`
2. `python3 scan.py server --loglevel=INFO`

**Logs**

Link to log gist of full error: [https://gist.github.com/tyhi/9b5f1c4ba12bdbbba9507b681fd1c431](https://gist.github.com/tyhi/9b5f1c4ba12bdbbba9507b681fd1c431).

**System Information**

 - Plex Autoscan Version: Master & Develop
 - Operating System: CentOS 8

**Comment by nemchik** [comment]
Try using `python` or `python2` instead of `python3`

**Comment by nayr1991** [comment]
I had the same issue and am using python2.7
```
Sep 17 21:08:05 mediabox scan.py[7877]:  2020-09-17 21:08:05,188 -    ERROR -    GOOGLE [140143977559808]: Exception sending request to https://www.googleapis.com/drive/v3/changes/startPageToken with kwargs={'params': {'supportsTeamDrives': False}}:
Sep 17 21:08:05 mediabox scan.py[7877]: Traceback (most recent call last):
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/opt/plex_autoscan/google/drive.py", line 148, in query
Sep 17 21:08:05 mediabox scan.py[7877]:     resp = self._do_query(request_url, method, **kwargs)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/opt/plex_autoscan/google/drive.py", line 435, in _do_query
Sep 17 21:08:05 mediabox scan.py[7877]:     resp = self.http.get(request_url, timeout=use_timeout, **kwargs)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
Sep 17 21:08:05 mediabox scan.py[7877]:     return self.request('GET', url, **kwargs)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 497, in request
Sep 17 21:08:05 mediabox scan.py[7877]:     self.auto_refresh_url, auth=auth, **kwargs
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
Sep 17 21:08:05 mediabox scan.py[7877]:     self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
Sep 17 21:08:05 mediabox scan.py[7877]:     self.token = parse_token_response(body, scope=scope)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
Sep 17 21:08:05 mediabox scan.py[7877]:     validate_token_parameters(params)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
Sep 17 21:08:05 mediabox scan.py[7877]:     raise_from_error(params.get('error'), params)
Sep 17 21:08:05 mediabox scan.py[7877]:   File "/usr/local/lib/python2.7/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
Sep 17 21:08:05 mediabox scan.py[7877]:     raise cls(**kwargs)
Sep 17 21:08:05 mediabox scan.py[7877]: UnauthorizedClientError: (unauthorized_client) Unauthorized
Sep 17 21:08:05 mediabox scan.py[7877]:  2020-09-17 21:08:05,191 -    ERROR -    GOOGLE [140143977559808]: Error validating access token, status_code = 0, data =
Sep 17 21:08:05 mediabox scan.py[7877]: None
Sep 17 21:08:05 mediabox scan.py[7877]:  2020-09-17 21:08:05,192 -    ERROR -  AUTOSCAN [140143977559808]: Failed to validate Google Drive Access Token.
```


Fix was to authorize access to this team drive by running `scan.py authorize` as per https://github.com/l3uddz/plex_autoscan#google-drive-monitoring
