### ISSUE TITLE
library path makes section mapping crash

### ISSUE THREAD

**Issue by j0shii** [l3uddz/plex_autoscan#164]
**Describe the bug**
when I put something new in drive, it generates an exception.

**To Reproduce**
add something to the drive

**Expected behavior**
Section mapping should be done properly.

**Logs**
ERROR -     UTILS [139967663843072]: Exception while trying to map 'Mi unidad/Joshua/Plex/Peliculas/Copia de El prado.mkv' to a Section ID in the Plex DB:
Traceback (most recent call last):
  File "/opt/plex_autoscan/utils.py", line 33, in get_plex_section
    if path.startswith(root_path + os.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 48: ordinal not in range(128)

**System Information**

 - Plex Autoscan Version: master
 - Operating System: Ubuntu Server 16.04 LTS

**Comment by Tomarok** [comment]
Same problem for me

**Comment by bison529** [comment]
I have same problem

 2021-04-11 22:30:23,302 -    ERROR -     UTILS [140261260793600]: Exception while trying to map '/mnt/unionfs/مسلسلات مصرية/مسلسل لحم غزال 2021/نسخة من Ep01.KOK.mkv' to a Section ID in the Plex DB:
Traceback (most recent call last):
  File "/opt/plex_autoscan/utils.py", line 33, in get_plex_section
    if path.startswith(root_path + os.sep):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 13: ordinal not in range(128)

**Comment by bison529** [comment]
I found this solution in Discord:

in utils.py in /plex_autoscan i added the following 2 lines :

reload(sys)
sys.setdefaultencoding("utf-8")

**Comment by Tomarok** [comment]
Work for me, thanks @bison529
