### ISSUE TITLE
python module import errors

### ISSUE THREAD

**Issue by snickers2k** [l3uddz/plex_autoscan#171]
Does this still work for anyone ? I'm getting import errors with python2 and python3 

python2
```
$ python2 /opt/plex_autoscan/scan.py server
Traceback (most recent call last):
  File "/opt/plex_autoscan/scan.py", line 8, in <module>
    from pyfiglet import Figlet
ImportError: No module named pyfiglet
```

python3.8
```
$ python3.8 /opt/plex_autoscan/scan.py server
 2022-01-19 19:27:20,402 -     INFO -    CONFIG [140579984410432]: Using default setting --config=/opt/plex_autoscan/config/config.json
 2022-01-19 19:27:20,403 -     INFO -    CONFIG [140579984410432]: Using default setting --logfile=/opt/plex_autoscan/plex_autoscan.log
 2022-01-19 19:27:20,403 -     INFO -    CONFIG [140579984410432]: Using default setting --loglevel=INFO
 2022-01-19 19:27:20,403 -     INFO -    CONFIG [140579984410432]: Using default setting --queuefile=/opt/plex_autoscan/queue.db
 2022-01-19 19:27:20,403 -     INFO -    CONFIG [140579984410432]: Using default setting --cachefile=/opt/plex_autoscan/cache.db
 2022-01-19 19:27:20,411 -     INFO -    CONFIG [140579984410432]: Using default setting --config=/opt/plex_autoscan/config/config.json
 2022-01-19 19:27:20,411 -     INFO -    CONFIG [140579984410432]: Using default setting --logfile=/opt/plex_autoscan/plex_autoscan.log
 2022-01-19 19:27:20,411 -     INFO -    CONFIG [140579984410432]: Using default setting --loglevel=INFO
 2022-01-19 19:27:20,411 -     INFO -    CONFIG [140579984410432]: Using default setting --queuefile=/opt/plex_autoscan/queue.db
 2022-01-19 19:27:20,411 -     INFO -    CONFIG [140579984410432]: Using default setting --cachefile=/opt/plex_autoscan/cache.db
Traceback (most recent call last):
  File "/opt/plex_autoscan/scan.py", line 80, in <module>
    from google import GoogleDrive, GoogleDriveManager
ImportError: cannot import name 'GoogleDrive' from 'google' (unknown location)
```
python3.9
```
python3.9 /opt/plex_autoscan/scan.py server
Traceback (most recent call last):
  File "/opt/plex_autoscan/scan.py", line 8, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'
```

other scripts from l3uddz are working great. so guess the problem is pyfiglet or GoogleDrive, which are both installed

is this updated to work with python3 ? or maybe someone could do this please?
thanks

**Comment by snickers2k** [comment]
hmm... don't know what the issue was, but the latest commit fixed it 👍
