### ISSUE TITLE
Multiple Remote paths

### ISSUE THREAD

**Issue by sbcrumb** [l3uddz/plex_autoscan#48]
Trying to get multiple remote paths remapped. But not having luck. What is the proper way to accomplish this?

```
  "SERVER_PATH_MAPPINGS": {
    "/mnt/unionfs/": [
      "/mnt/shared/Application Data/fusemounts/unionfs/"
     ],
      "/mnt/unionfs/": [
      "/mnt/shared/unionfs/"
   ]
  },
```

**Comment by desimaniac** [comment]
Trying to get multiple remote paths remapped. But not having luck. What is the proper way to accomplish this?

```
  "SERVER_PATH_MAPPINGS": {
    "/mnt/unionfs/": [
      "/mnt/shared/Application Data/fusemounts/unionfs/",
      "/mnt/shared/unionfs/"
   ]
  },
```

**Comment by sbcrumb** [comment]
tried that and get this
 2018-08-27 16:29:06,558 -     INFO -    CONFIG [140233358984960]: Using default setting --loglevel=INFO
 2018-08-27 16:29:06,558 -     INFO -    CONFIG [140233358984960]: Using default setting --cachefile=cache.db
 2018-08-27 16:29:06,558 -     INFO -    CONFIG [140233358984960]: Using default setting --tokenfile=token.json
 2018-08-27 16:29:06,558 -     INFO -    CONFIG [140233358984960]: Using default setting --queuefile=queue.db
 2018-08-27 16:29:06,558 -     INFO -    CONFIG [140233358984960]: Using default setting --logfile=plex_autoscan.log
 2018-08-27 16:29:06,558 -     INFO -    CONFIG [140233358984960]: Using default setting --config=config/config.json
Traceback (most recent call last):
  File "scan.py", line 56, in <module>
    conf.load()
  File "/opt/plex_autoscan/config.py", line 233, in load
    cfg, upgraded = self.upgrade_settings(json.load(fp))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 128 column 2 (char 2751)

**Comment by desimaniac** [comment]
Try validating your entire config file here:

https://jsonformatter.curiousconcept.com

**Comment by sbcrumb** [comment]
dang I am sorry that appears to have worked I fat fingered and added a space on the copy.
