### ISSUE TITLE
unable to authorize google drive

### ISSUE THREAD

**Issue by saitoh183** [l3uddz/plex_autoscan#58]
When i run the `scan.py authorize` i get the following
```
 2018-11-04 22:55:27,236 -     INFO -    CONFIG [140250178578176]: Using default setting --loglevel=INFO
 2018-11-04 22:55:27,236 -     INFO -    CONFIG [140250178578176]: Using default setting --cachefile=cache.db
 2018-11-04 22:55:27,237 -     INFO -    CONFIG [140250178578176]: Using default setting --tokenfile=token.json
 2018-11-04 22:55:27,237 -     INFO -    CONFIG [140250178578176]: Using default setting --queuefile=queue.db
 2018-11-04 22:55:27,237 -     INFO -    CONFIG [140250178578176]: Using default setting --logfile=plex_autoscan.log
 2018-11-04 22:55:27,237 -     INFO -    CONFIG [140250178578176]: Using default setting --config=config/config.json
Traceback (most recent call last):
  File "scan.py", line 56, in <module>
    conf.load()
  File "/scripts/plex_autoscan/config.py", line 237, in load
    cfg, upgraded = self.upgrade_settings(json.load(fp))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 89 column 3 (char 1971)
```

**Comment by saitoh183** [comment]
Thanks!

is the last line normal?
```
 2018-11-09 13:29:25,873 -     INFO -    GDRIVE [140167138195200]: Retrieved first access token!
 2018-11-09 13:29:25,876 -     INFO -  AUTOSCAN [140167138195200]: Access tokens were successfully retrieved!
Segmentation fault
```

**Comment by desimaniac** [comment]
Yeah it happens, occasionally, even when things are ok. Just ignore it.

**Comment by saitoh183** [comment]
cool thanks :)
