### ISSUE TITLE
Unicode Encode Error

### ISSUE THREAD

**Issue by xman0980** [l3uddz/plex_autoscan#73]
I keep getting this error when its scanning. Items still appear, but I get this error.

```Jan 26 17:11:29 s131265 scan.py[7564]: Traceback (most recent call last):
Jan 26 17:11:29 s131265 scan.py[7564]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Jan 26 17:11:29 s131265 scan.py[7564]:     self.run()
Jan 26 17:11:29 s131265 scan.py[7564]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Jan 26 17:11:29 s131265 scan.py[7564]:     self.__target(*self.__args, **self.__kwargs)
Jan 26 17:11:29 s131265 scan.py[7564]:   File "/opt/plex_autoscan/plex.py", line 61, in scan
Jan 26 17:11:29 s131265 scan.py[7564]:     scan_path_is_directory = os.path.isdir(check_path)
Jan 26 17:11:29 s131265 scan.py[7564]:   File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
Jan 26 17:11:29 s131265 scan.py[7564]:     st = os.stat(s)
Jan 26 17:11:29 s131265 scan.py[7564]: UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position 102: ordinal not in range(256)
```

it doesnt crash the script.

**Comment by saitoh183** [comment]
@l3uddz 

When doing a manual scan and i use a path with special caracters , i get 
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

But it still seems to go through

` 2019-02-27 03:04:16,348 -     INFO -  AUTOSCAN [139936281057088]: Client '172.20.0.4' made a manual scan request for: '/media/b33f/saitoh183/private/Videos/FrenchTV/L'échappée/Season 03'`

I will check if i get the same behavior running it in my python script.

**Comment by l3uddz** [comment]
This should be resolved with newer Autoscan (develop branch).

If not add `export PYTHONIOENCODING=UTF-8` to your bash.rc / .zshrc file(s)
